
#define _CRT_SECURE_NO_WARNINGS

#include <winsock2.h>
#include <ws2tcpip.h>
#include "windows.h"
#include "winternl.h"
#include <stdio.h>
#pragma comment (lib, "Ws2_32.lib")
#define FORWARDED_EXPORT_WITH_ORDINAL(exp_name, ordinal, target_name) __pragma (comment (linker, "/export:" #exp_name "=" #target_name ",@" #ordinal))

FORWARDED_EXPORT_WITH_ORDINAL(osdk_Allocator_Free, 1, osdk_orig.osdk_Allocator_Free)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Allocator_Init, 2, osdk_orig.osdk_Allocator_Init)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Allocator_Malloc, 3, osdk_orig.osdk_Allocator_Malloc)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Allocator_Realloc, 4, osdk_orig.osdk_Allocator_Realloc)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToDouble, 5, osdk_orig.osdk_AsciiToDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToFloat, 6, osdk_orig.osdk_AsciiToFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToInt16, 7, osdk_orig.osdk_AsciiToInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToInt32, 8, osdk_orig.osdk_AsciiToInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToInt64, 9, osdk_orig.osdk_AsciiToInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToInt8, 10, osdk_orig.osdk_AsciiToInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToUInt16, 11, osdk_orig.osdk_AsciiToUInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToUInt32, 12, osdk_orig.osdk_AsciiToUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToUInt64, 13, osdk_orig.osdk_AsciiToUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_AsciiToUInt8, 14, osdk_orig.osdk_AsciiToUInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Base64_Decode, 15, osdk_orig.osdk_Base64_Decode)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Base64_DecodeInPlace, 16, osdk_orig.osdk_Base64_DecodeInPlace)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Base64_Encode, 17, osdk_orig.osdk_Base64_Encode)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Base64_EncodeURLSafe, 18, osdk_orig.osdk_Base64_EncodeURLSafe)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ClientInfo_structSize, 19, osdk_orig.osdk_ClientInfo_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Create, 20, osdk_orig.osdk_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_DoubleToAscii, 21, osdk_orig.osdk_DoubleToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_DoubleToAsciiLength, 22, osdk_orig.osdk_DoubleToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_FloatToAscii, 23, osdk_orig.osdk_FloatToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_FloatToAsciiLength, 24, osdk_orig.osdk_FloatToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_SetDefaultLoggingFlags, 25, osdk_orig.osdk_HTTPClient_SetDefaultLoggingFlags)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_addBackFilter, 26, osdk_orig.osdk_HTTPClient_addBackFilter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_addFrontFilter, 27, osdk_orig.osdk_HTTPClient_addFrontFilter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_destruct, 28, osdk_orig.osdk_HTTPClient_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_enableBodyCompression, 29, osdk_orig.osdk_HTTPClient_enableBodyCompression)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_enableWebLogging, 30, osdk_orig.osdk_HTTPClient_enableWebLogging)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_executeAsync, 31, osdk_orig.osdk_HTTPClient_executeAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_releaseAsync, 32, osdk_orig.osdk_HTTPClient_releaseAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPClient_setLoggingFlags, 33, osdk_orig.osdk_HTTPClient_setLoggingFlags)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPFilter_Create, 34, osdk_orig.osdk_HTTPFilter_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaderNames_Get, 35, osdk_orig.osdk_HTTPHeaderNames_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaders_getKeyAt, 36, osdk_orig.osdk_HTTPHeaders_getKeyAt)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaders_getSize, 37, osdk_orig.osdk_HTTPHeaders_getSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaders_getValue, 38, osdk_orig.osdk_HTTPHeaders_getValue)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaders_getValueAt, 39, osdk_orig.osdk_HTTPHeaders_getValueAt)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPHeaders_setValue, 40, osdk_orig.osdk_HTTPHeaders_setValue)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_assignMove, 41, osdk_orig.osdk_HTTPRequestBuilder_assignMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_construct, 42, osdk_orig.osdk_HTTPRequestBuilder_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_constructMove, 43, osdk_orig.osdk_HTTPRequestBuilder_constructMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_construct_with_baseurl, 44, osdk_orig.osdk_HTTPRequestBuilder_construct_with_baseurl)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_destruct, 45, osdk_orig.osdk_HTTPRequestBuilder_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setBaseURL, 46, osdk_orig.osdk_HTTPRequestBuilder_setBaseURL)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setBody, 47, osdk_orig.osdk_HTTPRequestBuilder_setBody)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setConnectTimeout, 48, osdk_orig.osdk_HTTPRequestBuilder_setConnectTimeout)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setHeader, 49, osdk_orig.osdk_HTTPRequestBuilder_setHeader)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setParameter, 50, osdk_orig.osdk_HTTPRequestBuilder_setParameter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_setSerializationMilliseconds, 51, osdk_orig.osdk_HTTPRequestBuilder_setSerializationMilliseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequestBuilder_structSize, 52, osdk_orig.osdk_HTTPRequestBuilder_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPRequest_setHeader, 53, osdk_orig.osdk_HTTPRequest_setHeader)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_Create, 54, osdk_orig.osdk_HTTPResponse_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_addHeader, 55, osdk_orig.osdk_HTTPResponse_addHeader)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_destruct, 56, osdk_orig.osdk_HTTPResponse_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getDate, 57, osdk_orig.osdk_HTTPResponse_getDate)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getETag, 58, osdk_orig.osdk_HTTPResponse_getETag)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getFutureBody, 59, osdk_orig.osdk_HTTPResponse_getFutureBody)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getHeaders, 60, osdk_orig.osdk_HTTPResponse_getHeaders)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getMaxAge, 61, osdk_orig.osdk_HTTPResponse_getMaxAge)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getMessage, 62, osdk_orig.osdk_HTTPResponse_getMessage)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getReceivedAt, 63, osdk_orig.osdk_HTTPResponse_getReceivedAt)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_getStatusCode, 64, osdk_orig.osdk_HTTPResponse_getStatusCode)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPResponse_setStatus, 65, osdk_orig.osdk_HTTPResponse_setStatus)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_build, 66, osdk_orig.osdk_HTTPUserAgentBuilder_build)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_construct, 67, osdk_orig.osdk_HTTPUserAgentBuilder_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_destruct, 68, osdk_orig.osdk_HTTPUserAgentBuilder_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setApplicationDetail, 69, osdk_orig.osdk_HTTPUserAgentBuilder_setApplicationDetail)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setApplicationName, 70, osdk_orig.osdk_HTTPUserAgentBuilder_setApplicationName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setApplicationVersion, 71, osdk_orig.osdk_HTTPUserAgentBuilder_setApplicationVersion)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setExtension, 72, osdk_orig.osdk_HTTPUserAgentBuilder_setExtension)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setFrameworkDetail, 73, osdk_orig.osdk_HTTPUserAgentBuilder_setFrameworkDetail)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setFrameworkName, 74, osdk_orig.osdk_HTTPUserAgentBuilder_setFrameworkName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_HTTPUserAgentBuilder_setFrameworkVersion, 75, osdk_orig.osdk_HTTPUserAgentBuilder_setFrameworkVersion)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityProviders_Get, 76, osdk_orig.osdk_IdentityProviders_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityStore_clear, 77, osdk_orig.osdk_IdentityStore_clear)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityStore_getUserIdentity, 78, osdk_orig.osdk_IdentityStore_getUserIdentity)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityStore_registerIdentityProvider, 79, osdk_orig.osdk_IdentityStore_registerIdentityProvider)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityStore_storeIdentity, 80, osdk_orig.osdk_IdentityStore_storeIdentity)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityStore_unregisterIdentityProvider, 81, osdk_orig.osdk_IdentityStore_unregisterIdentityProvider)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_IdentityTokenTypes_Get, 82, osdk_orig.osdk_IdentityTokenTypes_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_assignMove, 83, osdk_orig.osdk_Identity_assignMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_construct, 84, osdk_orig.osdk_Identity_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_constructMove, 85, osdk_orig.osdk_Identity_constructMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_constructMoveUserId, 86, osdk_orig.osdk_Identity_constructMoveUserId)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_destruct, 87, osdk_orig.osdk_Identity_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_getAudienceURI, 88, osdk_orig.osdk_Identity_getAudienceURI)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_getExpiresAt, 89, osdk_orig.osdk_Identity_getExpiresAt)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_getToken, 90, osdk_orig.osdk_Identity_getToken)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_getTokenType, 91, osdk_orig.osdk_Identity_getTokenType)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_getUserId, 92, osdk_orig.osdk_Identity_getUserId)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_setExpiresAt, 93, osdk_orig.osdk_Identity_setExpiresAt)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_setToken, 94, osdk_orig.osdk_Identity_setToken)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Identity_structSize, 95, osdk_orig.osdk_Identity_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_FromMillisecondsSince1970UTC, 96, osdk_orig.osdk_Instant_FromMillisecondsSince1970UTC)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_FromSecondsSince1970UTC, 97, osdk_orig.osdk_Instant_FromSecondsSince1970UTC)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_Now, 98, osdk_orig.osdk_Instant_Now)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_Parse, 99, osdk_orig.osdk_Instant_Parse)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_ParseRFC822, 100, osdk_orig.osdk_Instant_ParseRFC822)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_SystemNow, 101, osdk_orig.osdk_Instant_SystemNow)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Instant_toISO8601String, 102, osdk_orig.osdk_Instant_toISO8601String)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Int32ToAscii, 103, osdk_orig.osdk_Int32ToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Int32ToAsciiLength, 104, osdk_orig.osdk_Int32ToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Int64ToAscii, 105, osdk_orig.osdk_Int64ToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Int64ToAsciiLength, 106, osdk_orig.osdk_Int64ToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_begin, 107, osdk_orig.osdk_JSONArray_begin)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_end, 108, osdk_orig.osdk_JSONArray_end)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_get, 109, osdk_orig.osdk_JSONArray_get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_isEmpty, 110, osdk_orig.osdk_JSONArray_isEmpty)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBack, 111, osdk_orig.osdk_JSONArray_pushBack)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackBool, 112, osdk_orig.osdk_JSONArray_pushBackBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackDouble, 113, osdk_orig.osdk_JSONArray_pushBackDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackFloat, 114, osdk_orig.osdk_JSONArray_pushBackFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackInt32, 115, osdk_orig.osdk_JSONArray_pushBackInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackInt64, 116, osdk_orig.osdk_JSONArray_pushBackInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackNull, 117, osdk_orig.osdk_JSONArray_pushBackNull)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackString, 118, osdk_orig.osdk_JSONArray_pushBackString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackUInt32, 119, osdk_orig.osdk_JSONArray_pushBackUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_pushBackUInt64, 120, osdk_orig.osdk_JSONArray_pushBackUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONArray_size, 121, osdk_orig.osdk_JSONArray_size)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_Create, 122, osdk_orig.osdk_JSONDocument_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_Parse, 123, osdk_orig.osdk_JSONDocument_Parse)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_destruct, 124, osdk_orig.osdk_JSONDocument_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_free, 125, osdk_orig.osdk_JSONDocument_free)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_getAllocator, 126, osdk_orig.osdk_JSONDocument_getAllocator)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONDocument_toString, 127, osdk_orig.osdk_JSONDocument_toString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_emplaceMember, 128, osdk_orig.osdk_JSONObject_emplaceMember)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_find, 129, osdk_orig.osdk_JSONObject_find)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_hasMember, 130, osdk_orig.osdk_JSONObject_hasMember)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_isEmpty, 131, osdk_orig.osdk_JSONObject_isEmpty)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMember, 132, osdk_orig.osdk_JSONObject_setMember)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberBool, 133, osdk_orig.osdk_JSONObject_setMemberBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberDouble, 134, osdk_orig.osdk_JSONObject_setMemberDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberFloat, 135, osdk_orig.osdk_JSONObject_setMemberFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberInt32, 136, osdk_orig.osdk_JSONObject_setMemberInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberInt64, 137, osdk_orig.osdk_JSONObject_setMemberInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberNull, 138, osdk_orig.osdk_JSONObject_setMemberNull)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberString, 139, osdk_orig.osdk_JSONObject_setMemberString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberUInt32, 140, osdk_orig.osdk_JSONObject_setMemberUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_setMemberUInt64, 141, osdk_orig.osdk_JSONObject_setMemberUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_size, 142, osdk_orig.osdk_JSONObject_size)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONObject_visitMembers, 143, osdk_orig.osdk_JSONObject_visitMembers)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asArray, 144, osdk_orig.osdk_JSONValue_asArray)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asBool, 145, osdk_orig.osdk_JSONValue_asBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asDouble, 146, osdk_orig.osdk_JSONValue_asDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asFloat, 147, osdk_orig.osdk_JSONValue_asFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asInt16, 148, osdk_orig.osdk_JSONValue_asInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asInt32, 149, osdk_orig.osdk_JSONValue_asInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asInt64, 150, osdk_orig.osdk_JSONValue_asInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asInt8, 151, osdk_orig.osdk_JSONValue_asInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asObject, 152, osdk_orig.osdk_JSONValue_asObject)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asString, 153, osdk_orig.osdk_JSONValue_asString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asUInt16, 154, osdk_orig.osdk_JSONValue_asUInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asUInt32, 155, osdk_orig.osdk_JSONValue_asUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asUInt64, 156, osdk_orig.osdk_JSONValue_asUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_asUInt8, 157, osdk_orig.osdk_JSONValue_asUInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_assignMove, 158, osdk_orig.osdk_JSONValue_assignMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_construct, 159, osdk_orig.osdk_JSONValue_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructBool, 160, osdk_orig.osdk_JSONValue_constructBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructDouble, 161, osdk_orig.osdk_JSONValue_constructDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructFloat, 162, osdk_orig.osdk_JSONValue_constructFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructInt32, 163, osdk_orig.osdk_JSONValue_constructInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructInt64, 164, osdk_orig.osdk_JSONValue_constructInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructMove, 165, osdk_orig.osdk_JSONValue_constructMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructNull, 166, osdk_orig.osdk_JSONValue_constructNull)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructString, 167, osdk_orig.osdk_JSONValue_constructString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructStringView, 168, osdk_orig.osdk_JSONValue_constructStringView)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructUInt32, 169, osdk_orig.osdk_JSONValue_constructUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_constructUInt64, 170, osdk_orig.osdk_JSONValue_constructUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_debug_getJSONTypeName, 171, osdk_orig.osdk_JSONValue_debug_getJSONTypeName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_destruct, 172, osdk_orig.osdk_JSONValue_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_getType, 173, osdk_orig.osdk_JSONValue_getType)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isArray, 174, osdk_orig.osdk_JSONValue_isArray)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isBool, 175, osdk_orig.osdk_JSONValue_isBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isNull, 176, osdk_orig.osdk_JSONValue_isNull)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isNumber, 177, osdk_orig.osdk_JSONValue_isNumber)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isObject, 178, osdk_orig.osdk_JSONValue_isObject)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_isString, 179, osdk_orig.osdk_JSONValue_isString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_moveValue, 180, osdk_orig.osdk_JSONValue_moveValue)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setArray, 181, osdk_orig.osdk_JSONValue_setArray)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setObject, 182, osdk_orig.osdk_JSONValue_setObject)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueBool, 183, osdk_orig.osdk_JSONValue_setValueBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueDouble, 184, osdk_orig.osdk_JSONValue_setValueDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueFloat, 185, osdk_orig.osdk_JSONValue_setValueFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueInt32, 186, osdk_orig.osdk_JSONValue_setValueInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueInt64, 187, osdk_orig.osdk_JSONValue_setValueInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueString, 188, osdk_orig.osdk_JSONValue_setValueString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueStringView, 189, osdk_orig.osdk_JSONValue_setValueStringView)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueUInt32, 190, osdk_orig.osdk_JSONValue_setValueUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_setValueUInt64, 191, osdk_orig.osdk_JSONValue_setValueUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_structSize, 192, osdk_orig.osdk_JSONValue_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_JSONValue_toString, 193, osdk_orig.osdk_JSONValue_toString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Lock_cleanup, 194, osdk_orig.osdk_Lock_cleanup)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Lock_initialize, 195, osdk_orig.osdk_Lock_initialize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Lock_lock, 196, osdk_orig.osdk_Lock_lock)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Lock_tryLock, 197, osdk_orig.osdk_Lock_tryLock)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Lock_unlock, 198, osdk_orig.osdk_Lock_unlock)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_LogAppenders_Log, 199, osdk_orig.osdk_LogAppenders_Log)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_LogAppenders_Register, 200, osdk_orig.osdk_LogAppenders_Register)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_LogAppenders_Unregister, 201, osdk_orig.osdk_LogAppenders_Unregister)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_LoggerAttributeKeys_Get, 202, osdk_orig.osdk_LoggerAttributeKeys_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Logger_GetLevel, 203, osdk_orig.osdk_Logger_GetLevel)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Logger_Log, 204, osdk_orig.osdk_Logger_Log)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Logger_ResetAll, 205, osdk_orig.osdk_Logger_ResetAll)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Logger_SetLevel, 206, osdk_orig.osdk_Logger_SetLevel)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Logger_logWithSourceInfo, 207, osdk_orig.osdk_Logger_logWithSourceInfo)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_cleanup, 208, osdk_orig.osdk_ManualSignal_cleanup)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_initialize, 209, osdk_orig.osdk_ManualSignal_initialize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_isSignaled, 210, osdk_orig.osdk_ManualSignal_isSignaled)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_signal, 211, osdk_orig.osdk_ManualSignal_signal)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_waitForever, 212, osdk_orig.osdk_ManualSignal_waitForever)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_waitMicroseconds, 213, osdk_orig.osdk_ManualSignal_waitMicroseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_waitMilliseconds, 214, osdk_orig.osdk_ManualSignal_waitMilliseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_waitNanoseconds, 215, osdk_orig.osdk_ManualSignal_waitNanoseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ManualSignal_waitSeconds, 216, osdk_orig.osdk_ManualSignal_waitSeconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MediaTypeNames_Get, 217, osdk_orig.osdk_MediaTypeNames_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_addBackFilter, 218, osdk_orig.osdk_MetricQueue_addBackFilter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_addFrontFilter, 219, osdk_orig.osdk_MetricQueue_addFrontFilter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_enqueue, 220, osdk_orig.osdk_MetricQueue_enqueue)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_flush, 221, osdk_orig.osdk_MetricQueue_flush)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_getCapacity, 222, osdk_orig.osdk_MetricQueue_getCapacity)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_getDefaultFlushTimeoutMS, 223, osdk_orig.osdk_MetricQueue_getDefaultFlushTimeoutMS)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_getMaxFlushTimeoutMS, 224, osdk_orig.osdk_MetricQueue_getMaxFlushTimeoutMS)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_getSize, 225, osdk_orig.osdk_MetricQueue_getSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_removeFilter, 226, osdk_orig.osdk_MetricQueue_removeFilter)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_setCapacity, 227, osdk_orig.osdk_MetricQueue_setCapacity)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_setDefaultFlushTimeoutMS, 228, osdk_orig.osdk_MetricQueue_setDefaultFlushTimeoutMS)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_MetricQueue_setMaxFlushTimeoutMS, 229, osdk_orig.osdk_MetricQueue_setMaxFlushTimeoutMS)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ObjectId_Parse, 230, osdk_orig.osdk_ObjectId_Parse)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ObjectId_structSize, 231, osdk_orig.osdk_ObjectId_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ObjectId_toString, 232, osdk_orig.osdk_ObjectId_toString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_OsdkInfo_structSize, 233, osdk_orig.osdk_OsdkInfo_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ProfileId_structSize, 234, osdk_orig.osdk_ProfileId_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Random_Fill, 235, osdk_orig.osdk_Random_Fill)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Random_Init, 236, osdk_orig.osdk_Random_Init)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_addProcessCallback, 237, osdk_orig.osdk_Scheduler_addProcessCallback)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_construct, 238, osdk_orig.osdk_Scheduler_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_destruct, 239, osdk_orig.osdk_Scheduler_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_executeAsync, 240, osdk_orig.osdk_Scheduler_executeAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_getFutureIdle, 241, osdk_orig.osdk_Scheduler_getFutureIdle)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_isCurrent, 242, osdk_orig.osdk_Scheduler_isCurrent)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_process, 243, osdk_orig.osdk_Scheduler_process)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_setClosing, 244, osdk_orig.osdk_Scheduler_setClosing)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Scheduler_terminateAsync, 245, osdk_orig.osdk_Scheduler_terminateAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_SchemaTypeNames_Get, 246, osdk_orig.osdk_SchemaTypeNames_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_ServerInfo_structSize, 247, osdk_orig.osdk_ServerInfo_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_cleanup, 248, osdk_orig.osdk_Signal_cleanup)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_initialize, 249, osdk_orig.osdk_Signal_initialize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_isSignaled, 250, osdk_orig.osdk_Signal_isSignaled)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_signal, 251, osdk_orig.osdk_Signal_signal)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_waitForever, 252, osdk_orig.osdk_Signal_waitForever)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_waitMicroseconds, 253, osdk_orig.osdk_Signal_waitMicroseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_waitMilliseconds, 254, osdk_orig.osdk_Signal_waitMilliseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_waitNanoseconds, 255, osdk_orig.osdk_Signal_waitNanoseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Signal_waitSeconds, 256, osdk_orig.osdk_Signal_waitSeconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_SmallString_structSize, 257, osdk_orig.osdk_SmallString_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_SpecialLoggers_Get, 258, osdk_orig.osdk_SpecialLoggers_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Statistics_structSize, 259, osdk_orig.osdk_Statistics_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_StringView_structSize, 260, osdk_orig.osdk_StringView_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_assign, 261, osdk_orig.osdk_String_assign)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_assignCString, 262, osdk_orig.osdk_String_assignCString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_assignCopyBeginEnd, 263, osdk_orig.osdk_String_assignCopyBeginEnd)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_assignMove, 264, osdk_orig.osdk_String_assignMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_begin, 265, osdk_orig.osdk_String_begin)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_compare, 266, osdk_orig.osdk_String_compare)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_construct, 267, osdk_orig.osdk_String_construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_constructCopy, 268, osdk_orig.osdk_String_constructCopy)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_constructCopyBeginEnd, 269, osdk_orig.osdk_String_constructCopyBeginEnd)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_constructCopyCStr, 270, osdk_orig.osdk_String_constructCopyCStr)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_constructMove, 271, osdk_orig.osdk_String_constructMove)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_constructWithSize, 272, osdk_orig.osdk_String_constructWithSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_data, 273, osdk_orig.osdk_String_data)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_destruct, 274, osdk_orig.osdk_String_destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_emptyRef, 275, osdk_orig.osdk_String_emptyRef)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_end, 276, osdk_orig.osdk_String_end)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_equals, 277, osdk_orig.osdk_String_equals)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_equalsCStr, 278, osdk_orig.osdk_String_equalsCStr)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_equalsStringView, 279, osdk_orig.osdk_String_equalsStringView)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_findStringView, 280, osdk_orig.osdk_String_findStringView)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_isEmpty, 281, osdk_orig.osdk_String_isEmpty)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_length, 282, osdk_orig.osdk_String_length)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_resize, 283, osdk_orig.osdk_String_resize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_rfindStringView, 284, osdk_orig.osdk_String_rfindStringView)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_String_structSize, 285, osdk_orig.osdk_String_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_TaskContinuation_structSize, 286, osdk_orig.osdk_TaskContinuation_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_Create, 287, osdk_orig.osdk_Task_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_Delete, 288, osdk_orig.osdk_Task_Delete)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_addContinuation, 289, osdk_orig.osdk_Task_addContinuation)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_cancel, 290, osdk_orig.osdk_Task_cancel)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_cancelChain, 291, osdk_orig.osdk_Task_cancelChain)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_fail, 292, osdk_orig.osdk_Task_fail)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_failWithStatus, 293, osdk_orig.osdk_Task_failWithStatus)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_finish, 294, osdk_orig.osdk_Task_finish)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_getFailureStatus, 295, osdk_orig.osdk_Task_getFailureStatus)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_getStatus, 296, osdk_orig.osdk_Task_getStatus)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_getValuePtr, 297, osdk_orig.osdk_Task_getValuePtr)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_movePtr, 298, osdk_orig.osdk_Task_movePtr)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_moveString, 299, osdk_orig.osdk_Task_moveString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_release, 300, osdk_orig.osdk_Task_release)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_retain, 301, osdk_orig.osdk_Task_retain)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_setIsContinuationOf, 302, osdk_orig.osdk_Task_setIsContinuationOf)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_waitForever, 303, osdk_orig.osdk_Task_waitForever)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Task_waitMilliseconds, 304, osdk_orig.osdk_Task_waitMilliseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UInt32ToAscii, 305, osdk_orig.osdk_UInt32ToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UInt32ToAsciiLength, 306, osdk_orig.osdk_UInt32ToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UInt64ToAscii, 307, osdk_orig.osdk_UInt64ToAscii)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UInt64ToAsciiLength, 308, osdk_orig.osdk_UInt64ToAsciiLength)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UUID_Parse, 309, osdk_orig.osdk_UUID_Parse)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UUID_Random, 310, osdk_orig.osdk_UUID_Random)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UUID_structSize, 311, osdk_orig.osdk_UUID_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UUID_toString, 312, osdk_orig.osdk_UUID_toString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UserAccountType_Get, 313, osdk_orig.osdk_UserAccountType_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UserId_structSize, 314, osdk_orig.osdk_UserId_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UserInfo_constructCopy, 315, osdk_orig.osdk_UserInfo_constructCopy)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UserInfo_move, 316, osdk_orig.osdk_UserInfo_move)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_UserInfo_structSize, 317, osdk_orig.osdk_UserInfo_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_Construct, 318, osdk_orig.osdk_Variant_Construct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructBool, 319, osdk_orig.osdk_Variant_ConstructBool)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructDouble, 320, osdk_orig.osdk_Variant_ConstructDouble)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructFloat, 321, osdk_orig.osdk_Variant_ConstructFloat)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructInstant, 322, osdk_orig.osdk_Variant_ConstructInstant)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructInt16, 323, osdk_orig.osdk_Variant_ConstructInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructInt32, 324, osdk_orig.osdk_Variant_ConstructInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructInt64, 325, osdk_orig.osdk_Variant_ConstructInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructInt8, 326, osdk_orig.osdk_Variant_ConstructInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructObjectId, 327, osdk_orig.osdk_Variant_ConstructObjectId)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructString, 328, osdk_orig.osdk_Variant_ConstructString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructUInt16, 329, osdk_orig.osdk_Variant_ConstructUInt16)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructUInt32, 330, osdk_orig.osdk_Variant_ConstructUInt32)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructUInt64, 331, osdk_orig.osdk_Variant_ConstructUInt64)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructUInt8, 332, osdk_orig.osdk_Variant_ConstructUInt8)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_ConstructUUID, 333, osdk_orig.osdk_Variant_ConstructUUID)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_Destruct, 334, osdk_orig.osdk_Variant_Destruct)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Variant_structSize, 335, osdk_orig.osdk_Variant_structSize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_VersionValues_Get, 336, osdk_orig.osdk_VersionValues_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Version_Parse, 337, osdk_orig.osdk_Version_Parse)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Version_fromParts, 338, osdk_orig.osdk_Version_fromParts)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_Version_toString, 339, osdk_orig.osdk_Version_toString)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientAttributeKeys_Get, 340, osdk_orig.osdk_WebServiceClientAttributeKeys_Get)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_Create, 341, osdk_orig.osdk_WebServiceClientBuilder_Create)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_build, 342, osdk_orig.osdk_WebServiceClientBuilder_build)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_buildWithIdentity, 343, osdk_orig.osdk_WebServiceClientBuilder_buildWithIdentity)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_clearGlobalHeaders, 344, osdk_orig.osdk_WebServiceClientBuilder_clearGlobalHeaders)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getAttribute, 345, osdk_orig.osdk_WebServiceClientBuilder_getAttribute)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getConfigSandbox, 346, osdk_orig.osdk_WebServiceClientBuilder_getConfigSandbox)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getLoginURL, 347, osdk_orig.osdk_WebServiceClientBuilder_getLoginURL)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getOSDK, 348, osdk_orig.osdk_WebServiceClientBuilder_getOSDK)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getProjectName, 349, osdk_orig.osdk_WebServiceClientBuilder_getProjectName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getRevision, 350, osdk_orig.osdk_WebServiceClientBuilder_getRevision)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getSignupURL, 351, osdk_orig.osdk_WebServiceClientBuilder_getSignupURL)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_getUserSandbox, 352, osdk_orig.osdk_WebServiceClientBuilder_getUserSandbox)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_release, 353, osdk_orig.osdk_WebServiceClientBuilder_release)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setAttribute, 354, osdk_orig.osdk_WebServiceClientBuilder_setAttribute)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setConfigSandbox, 355, osdk_orig.osdk_WebServiceClientBuilder_setConfigSandbox)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setGlobalHeader, 356, osdk_orig.osdk_WebServiceClientBuilder_setGlobalHeader)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setRevision, 357, osdk_orig.osdk_WebServiceClientBuilder_setRevision)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setSignupURL, 358, osdk_orig.osdk_WebServiceClientBuilder_setSignupURL)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClientBuilder_setUserSandbox, 359, osdk_orig.osdk_WebServiceClientBuilder_setUserSandbox)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_addStatisticsDeserializationMilliseconds, 360, osdk_orig.osdk_WebServiceClient_addStatisticsDeserializationMilliseconds)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_attemptInitialize, 361, osdk_orig.osdk_WebServiceClient_attemptInitialize)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_executeAsync, 362, osdk_orig.osdk_WebServiceClient_executeAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getClientInfo, 363, osdk_orig.osdk_WebServiceClient_getClientInfo)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getFeatureSetting, 364, osdk_orig.osdk_WebServiceClient_getFeatureSetting)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getHTTPClient, 365, osdk_orig.osdk_WebServiceClient_getHTTPClient)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getIdentityStore, 366, osdk_orig.osdk_WebServiceClient_getIdentityStore)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getLastAuthenticationStatus, 367, osdk_orig.osdk_WebServiceClient_getLastAuthenticationStatus)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getLocalStorage, 368, osdk_orig.osdk_WebServiceClient_getLocalStorage)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getMembershipAccount, 369, osdk_orig.osdk_WebServiceClient_getMembershipAccount)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getMetricQueue, 370, osdk_orig.osdk_WebServiceClient_getMetricQueue)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getOSDK, 371, osdk_orig.osdk_WebServiceClient_getOSDK)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getOrCreateLocalStorage, 372, osdk_orig.osdk_WebServiceClient_getOrCreateLocalStorage)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getPrimaryProfileId, 373, osdk_orig.osdk_WebServiceClient_getPrimaryProfileId)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getServerInfo, 374, osdk_orig.osdk_WebServiceClient_getServerInfo)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getTokenAsync, 375, osdk_orig.osdk_WebServiceClient_getTokenAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getUserConsentsToSendingMetrics, 376, osdk_orig.osdk_WebServiceClient_getUserConsentsToSendingMetrics)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_getUserInfo, 377, osdk_orig.osdk_WebServiceClient_getUserInfo)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_isAuthenticated, 378, osdk_orig.osdk_WebServiceClient_isAuthenticated)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_refreshTokenAsync, 379, osdk_orig.osdk_WebServiceClient_refreshTokenAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_releaseAsync, 380, osdk_orig.osdk_WebServiceClient_releaseAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_resetAllLocalStorages, 381, osdk_orig.osdk_WebServiceClient_resetAllLocalStorages)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_resetLocalStorage, 382, osdk_orig.osdk_WebServiceClient_resetLocalStorage)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_setDefaultHeader, 383, osdk_orig.osdk_WebServiceClient_setDefaultHeader)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_setLanguage, 384, osdk_orig.osdk_WebServiceClient_setLanguage)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_setUserConsentsToSendingMetrics, 385, osdk_orig.osdk_WebServiceClient_setUserConsentsToSendingMetrics)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_WebServiceClient_terminateAsync, 386, osdk_orig.osdk_WebServiceClient_terminateAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_addProcessCallback, 387, osdk_orig.osdk_addProcessCallback)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_beginNewGameSession, 388, osdk_orig.osdk_beginNewGameSession)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_createHTTPClient, 389, osdk_orig.osdk_createHTTPClient)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_createWebServiceClientBuilder, 390, osdk_orig.osdk_createWebServiceClientBuilder)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getAndResetStatistics, 391, osdk_orig.osdk_getAndResetStatistics)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getBuiltInHTTPClientFactory, 392, osdk_orig.osdk_getBuiltInHTTPClientFactory)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getDestroyedEvent, 393, osdk_orig.osdk_getDestroyedEvent)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getHardwareName, 394, osdk_orig.osdk_getHardwareName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getIdentityStore, 395, osdk_orig.osdk_getIdentityStore)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getInfo, 396, osdk_orig.osdk_getInfo)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getSessionId, 397, osdk_orig.osdk_getSessionId)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getStatistics, 398, osdk_orig.osdk_getStatistics)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_getTerminatedEvent, 399, osdk_orig.osdk_getTerminatedEvent)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_initializeAsync, 400, osdk_orig.osdk_initializeAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_isNetworkAvailable, 401, osdk_orig.osdk_isNetworkAvailable)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_pauseGameSimulation, 402, osdk_orig.osdk_pauseGameSimulation)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_process, 403, osdk_orig.osdk_process)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_release, 404, osdk_orig.osdk_release)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_setApplicationDetail, 405, osdk_orig.osdk_setApplicationDetail)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_setHTTPClientFactory, 406, osdk_orig.osdk_setHTTPClientFactory)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_setHardwareName, 407, osdk_orig.osdk_setHardwareName)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_setNetworkStatusDelegate, 408, osdk_orig.osdk_setNetworkStatusDelegate)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_startGameSimulation, 409, osdk_orig.osdk_startGameSimulation)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_terminateAsync, 410, osdk_orig.osdk_terminateAsync)
FORWARDED_EXPORT_WITH_ORDINAL(osdk_update, 411, osdk_orig.osdk_update)

#include <stdint.h>


FILE* packets = NULL;
FILE* read_file = NULL;
FILE* write_file = NULL;
#define logger(x, ...) { \
		printf(x, __VA_ARGS__);\
}

//fprintf(packets, x, __VA_ARGS__); 


uint8_t shellcode[] = {
	0x48, 0xb8,
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x50, 0xc3
};


typedef DWORD64(*getHandle)(LPSTR str);
getHandle gethandle = 0x00007FFF65D21770;
void HookFunc(LPVOID address, LPVOID newAddr, const char* reason) {

	memcpy(address, shellcode, sizeof(shellcode));
	memcpy(((BYTE*)address) + 2, &newAddr, sizeof(LPVOID));

	logger("Hooked %p for: %s", address, reason);
}



typedef DWORD64(*Curl_vsetopt)(void* data, DWORD64 option, va_list param);
Curl_vsetopt curl_vsetopt_orig = NULL;


#define CURLOPTTYPE_LONG          0
#define CURLOPTTYPE_OBJECTPOINT   10000
#define CURLOPTTYPE_FUNCTIONPOINT 20000
#define CURLOPTTYPE_OFF_T         30000
#define CURLOPTTYPE_BLOB          40000
#define CURLOPTTYPE_STRINGPOINT  CURLOPTTYPE_OBJECTPOINT
#define CURLOPTTYPE_SLISTPOINT  CURLOPTTYPE_OBJECTPOINT
#define CURLOPT(name, ignore, index) \
	name = ignore+index

#define CURLOPT_CASE(name, ignore, ignore1) \
	case name:\
	logger("setopt: %s (%d)\n", #name, name);\
	break;


enum tmp {
	CURLOPT(CURLOPT_WRITEDATA, CURLOPTTYPE_OBJECTPOINT, 1)			  ,
																	  
	CURLOPT(CURLOPT_URL, CURLOPTTYPE_STRINGPOINT, 2)				  ,
																	  
	CURLOPT(CURLOPT_PORT, CURLOPTTYPE_LONG, 3)						  ,
																	  
	CURLOPT(CURLOPT_PROXY, CURLOPTTYPE_STRINGPOINT, 4)				  ,
																	  
	CURLOPT(CURLOPT_USERPWD, CURLOPTTYPE_STRINGPOINT, 5)			  ,
																	  
	CURLOPT(CURLOPT_PROXYUSERPWD, CURLOPTTYPE_STRINGPOINT, 6)		  ,
																	  
	CURLOPT(CURLOPT_RANGE, CURLOPTTYPE_STRINGPOINT, 7)				  ,
																	  
																	  
	CURLOPT(CURLOPT_READDATA, CURLOPTTYPE_OBJECTPOINT, 9)			  ,
																	  
	CURLOPT(CURLOPT_ERRORBUFFER, CURLOPTTYPE_OBJECTPOINT, 10)		  ,
																	  
	CURLOPT(CURLOPT_WRITEFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 11)	  ,
																	  
	CURLOPT(CURLOPT_READFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 12)	  ,
																	  
	CURLOPT(CURLOPT_TIMEOUT, CURLOPTTYPE_LONG, 13)					  ,
																	  
	CURLOPT(CURLOPT_INFILESIZE, CURLOPTTYPE_LONG, 14)				  ,
																	  
	CURLOPT(CURLOPT_POSTFIELDS, CURLOPTTYPE_OBJECTPOINT, 15)		  ,
																	  
	CURLOPT(CURLOPT_REFERER, CURLOPTTYPE_STRINGPOINT, 16)			  ,
																	  
	CURLOPT(CURLOPT_FTPPORT, CURLOPTTYPE_STRINGPOINT, 17)			  ,
																	  
	CURLOPT(CURLOPT_USERAGENT, CURLOPTTYPE_STRINGPOINT, 18)			  ,
																	  
																	  
	CURLOPT(CURLOPT_LOW_SPEED_LIMIT, CURLOPTTYPE_LONG, 19)			  ,
																	  
	CURLOPT(CURLOPT_LOW_SPEED_TIME, CURLOPTTYPE_LONG, 20)			  ,
																	  
	CURLOPT(CURLOPT_RESUME_FROM, CURLOPTTYPE_LONG, 21)				  ,
																	  
	CURLOPT(CURLOPT_COOKIE, CURLOPTTYPE_STRINGPOINT, 22)			  ,
																	  
	CURLOPT(CURLOPT_HTTPHEADER, CURLOPTTYPE_SLISTPOINT, 23)			  ,
																	  
	CURLOPT(CURLOPT_HTTPPOST, CURLOPTTYPE_OBJECTPOINT, 24)			  ,
																	  
	CURLOPT(CURLOPT_SSLCERT, CURLOPTTYPE_STRINGPOINT, 25)			  ,
																	  
	CURLOPT(CURLOPT_KEYPASSWD, CURLOPTTYPE_STRINGPOINT, 26)			  ,
																	  
	CURLOPT(CURLOPT_CRLF, CURLOPTTYPE_LONG, 27)						  ,
																	  
	CURLOPT(CURLOPT_QUOTE, CURLOPTTYPE_SLISTPOINT, 28)				  ,
																	  
	CURLOPT(CURLOPT_HEADERDATA, CURLOPTTYPE_OBJECTPOINT, 29)		  ,
																	  
	CURLOPT(CURLOPT_COOKIEFILE, CURLOPTTYPE_STRINGPOINT, 31)		  ,
																	  
	CURLOPT(CURLOPT_SSLVERSION, CURLOPTTYPE_LONG, 32)				  ,
																	  
	CURLOPT(CURLOPT_TIMECONDITION, CURLOPTTYPE_LONG, 33)			  ,
																	  
	CURLOPT(CURLOPT_TIMEVALUE, CURLOPTTYPE_LONG, 34)				  ,
																	  
																	  
	CURLOPT(CURLOPT_CUSTOMREQUEST, CURLOPTTYPE_STRINGPOINT, 36)		  ,
																	  
	CURLOPT(CURLOPT_STDERR, CURLOPTTYPE_OBJECTPOINT, 37)			  ,
																	  
																	  
	CURLOPT(CURLOPT_POSTQUOTE, CURLOPTTYPE_SLISTPOINT, 39)			  ,
																	  
	CURLOPT(CURLOPT_OBSOLETE40, CURLOPTTYPE_OBJECTPOINT, 40)		  ,
																	  
	CURLOPT(CURLOPT_VERBOSE, CURLOPTTYPE_LONG, 41)					  ,
																	  
	CURLOPT(CURLOPT_HEADER, CURLOPTTYPE_LONG, 42)					  ,
																	  
	CURLOPT(CURLOPT_NOPROGRESS, CURLOPTTYPE_LONG, 43)				  ,
																	  
	CURLOPT(CURLOPT_NOBODY, CURLOPTTYPE_LONG, 44)					  ,
																	  
	CURLOPT(CURLOPT_FAILONERROR, CURLOPTTYPE_LONG, 45)				  ,
																	  
	CURLOPT(CURLOPT_UPLOAD, CURLOPTTYPE_LONG, 46)					  ,
																	  
	CURLOPT(CURLOPT_POST, CURLOPTTYPE_LONG, 47)						  ,
																	  
	CURLOPT(CURLOPT_DIRLISTONLY, CURLOPTTYPE_LONG, 48)				  ,
																	  
	CURLOPT(CURLOPT_APPEND, CURLOPTTYPE_LONG, 50)					  ,
																	  
	CURLOPT(CURLOPT_NETRC, CURLOPTTYPE_LONG, 51)					  ,
																	  
	CURLOPT(CURLOPT_FOLLOWLOCATION, CURLOPTTYPE_LONG, 52)			  ,
																	  
	CURLOPT(CURLOPT_TRANSFERTEXT, CURLOPTTYPE_LONG, 53)				  ,
																	  
	CURLOPT(CURLOPT_PUT, CURLOPTTYPE_LONG, 54)						  ,
																	  
																	  
	CURLOPT(CURLOPT_PROGRESSFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 56)  ,
																	  
	CURLOPT(CURLOPT_PROGRESSDATA, CURLOPTTYPE_OBJECTPOINT, 57)		  ,
																	  
																	  
	CURLOPT(CURLOPT_AUTOREFERER, CURLOPTTYPE_LONG, 58)				  ,
																	  
	CURLOPT(CURLOPT_PROXYPORT, CURLOPTTYPE_LONG, 59)				  ,
																	  
	CURLOPT(CURLOPT_POSTFIELDSIZE, CURLOPTTYPE_LONG, 60)			  ,
																	  
	CURLOPT(CURLOPT_HTTPPROXYTUNNEL, CURLOPTTYPE_LONG, 61)			  ,
																	  
	CURLOPT(CURLOPT_INTERFACE, CURLOPTTYPE_STRINGPOINT, 62)			  ,
																	  
	CURLOPT(CURLOPT_KRBLEVEL, CURLOPTTYPE_STRINGPOINT, 63)			  ,
																	  
	CURLOPT(CURLOPT_SSL_VERIFYPEER, CURLOPTTYPE_LONG, 64)			  ,
																	  
	CURLOPT(CURLOPT_CAINFO, CURLOPTTYPE_STRINGPOINT, 65)			  ,
																	  
																	  
	CURLOPT(CURLOPT_MAXREDIRS, CURLOPTTYPE_LONG, 68)				  ,
																	  
	CURLOPT(CURLOPT_FILETIME, CURLOPTTYPE_LONG, 69)					  ,
																	  
	CURLOPT(CURLOPT_TELNETOPTIONS, CURLOPTTYPE_SLISTPOINT, 70)		  ,
																	  
	CURLOPT(CURLOPT_MAXCONNECTS, CURLOPTTYPE_LONG, 71)				  ,
																	  
	CURLOPT(CURLOPT_OBSOLETE72, CURLOPTTYPE_LONG, 72)				  ,
																	  
																	  
	CURLOPT(CURLOPT_FRESH_CONNECT, CURLOPTTYPE_LONG, 74)			  ,
																	  
	CURLOPT(CURLOPT_FORBID_REUSE, CURLOPTTYPE_LONG, 75)				  ,
																	  
	CURLOPT(CURLOPT_RANDOM_FILE, CURLOPTTYPE_STRINGPOINT, 76)		  ,
																	  
	CURLOPT(CURLOPT_EGDSOCKET, CURLOPTTYPE_STRINGPOINT, 77)			  ,
																	  
	CURLOPT(CURLOPT_CONNECTTIMEOUT, CURLOPTTYPE_LONG, 78)			  ,
																	  
	CURLOPT(CURLOPT_HEADERFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 79)	  ,
																	  
	CURLOPT(CURLOPT_HTTPGET, CURLOPTTYPE_LONG, 80)					  ,
																	  
	CURLOPT(CURLOPT_SSL_VERIFYHOST, CURLOPTTYPE_LONG, 81)			  ,
																	  
	CURLOPT(CURLOPT_COOKIEJAR, CURLOPTTYPE_STRINGPOINT, 82)			  ,
																	  
	CURLOPT(CURLOPT_SSL_CIPHER_LIST, CURLOPTTYPE_STRINGPOINT, 83)	  ,
																	  
	CURLOPT(CURLOPT_HTTP_VERSION, CURLOPTTYPE_LONG, 84)				  ,
																	  
	CURLOPT(CURLOPT_FTP_USE_EPSV, CURLOPTTYPE_LONG, 85)				  ,
																	  
	CURLOPT(CURLOPT_SSLCERTTYPE, CURLOPTTYPE_STRINGPOINT, 86)		  ,
																	  
	CURLOPT(CURLOPT_SSLKEY, CURLOPTTYPE_STRINGPOINT, 87)			  ,
																	  
	CURLOPT(CURLOPT_SSLKEYTYPE, CURLOPTTYPE_STRINGPOINT, 88)		  ,
																	  
	CURLOPT(CURLOPT_SSLENGINE, CURLOPTTYPE_STRINGPOINT, 89)			  ,
																	  
	CURLOPT(CURLOPT_SSLENGINE_DEFAULT, CURLOPTTYPE_LONG, 90)		  ,
																	  
	CURLOPT(CURLOPT_DNS_USE_GLOBAL_CACHE, CURLOPTTYPE_LONG, 91)		  ,
																	  
	CURLOPT(CURLOPT_DNS_CACHE_TIMEOUT, CURLOPTTYPE_LONG, 92)		  ,
																	  
	CURLOPT(CURLOPT_PREQUOTE, CURLOPTTYPE_SLISTPOINT, 93)			  ,
																	  
	CURLOPT(CURLOPT_DEBUGFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 94)	  ,
																	  
	CURLOPT(CURLOPT_DEBUGDATA, CURLOPTTYPE_OBJECTPOINT, 95)			  ,
																	  
	CURLOPT(CURLOPT_COOKIESESSION, CURLOPTTYPE_LONG, 96)			  ,
																	  
	CURLOPT(CURLOPT_CAPATH, CURLOPTTYPE_STRINGPOINT, 97)			  ,
																	  
	CURLOPT(CURLOPT_BUFFERSIZE, CURLOPTTYPE_LONG, 98)				  ,
																	  
	CURLOPT(CURLOPT_NOSIGNAL, CURLOPTTYPE_LONG, 99)					  ,
																	  
	CURLOPT(CURLOPT_SHARE, CURLOPTTYPE_OBJECTPOINT, 100)			  ,
																	  
	CURLOPT(CURLOPT_PROXYTYPE, CURLOPTTYPE_LONG, 101)				  ,
																	  
	CURLOPT(CURLOPT_ACCEPT_ENCODING, CURLOPTTYPE_STRINGPOINT, 102)	  ,
																	  
	CURLOPT(CURLOPT_PRIVATE, CURLOPTTYPE_OBJECTPOINT, 103)			  ,
																	  
	CURLOPT(CURLOPT_HTTP200ALIASES, CURLOPTTYPE_SLISTPOINT, 104)	  ,
																	  
	CURLOPT(CURLOPT_UNRESTRICTED_AUTH, CURLOPTTYPE_LONG, 105)		  ,
																	  
	CURLOPT(CURLOPT_FTP_USE_EPRT, CURLOPTTYPE_LONG, 106)			  ,
																	  
	CURLOPT(CURLOPT_HTTPAUTH, CURLOPTTYPE_LONG, 107)				  ,
																	  
	CURLOPT(CURLOPT_SSL_CTX_FUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 108) ,
																	  
	CURLOPT(CURLOPT_SSL_CTX_DATA, CURLOPTTYPE_OBJECTPOINT, 109)		  ,
																	  
	CURLOPT(CURLOPT_FTP_CREATE_MISSING_DIRS, CURLOPTTYPE_LONG, 110)	  ,
																	  
	CURLOPT(CURLOPT_PROXYAUTH, CURLOPTTYPE_LONG, 111)				  ,

	CURLOPT(CURLOPT_FTP_RESPONSE_TIMEOUT, CURLOPTTYPE_LONG, 112)


};

void print_setopt(DWORD64 tag) {
	switch (tag) {
			CURLOPT_CASE(CURLOPT_WRITEDATA, CURLOPT_CASETYPE_OBJECTPOINT, 1)

			CURLOPT_CASE(CURLOPT_URL, CURLOPT_CASETYPE_STRINGPOINT, 2)

			CURLOPT_CASE(CURLOPT_PORT, CURLOPT_CASETYPE_LONG, 3)

			CURLOPT_CASE(CURLOPT_PROXY, CURLOPT_CASETYPE_STRINGPOINT, 4)

			CURLOPT_CASE(CURLOPT_USERPWD, CURLOPT_CASETYPE_STRINGPOINT, 5)

			CURLOPT_CASE(CURLOPT_PROXYUSERPWD, CURLOPT_CASETYPE_STRINGPOINT, 6)

			CURLOPT_CASE(CURLOPT_RANGE, CURLOPT_CASETYPE_STRINGPOINT, 7)


			CURLOPT_CASE(CURLOPT_READDATA, CURLOPT_CASETYPE_OBJECTPOINT, 9)

			CURLOPT_CASE(CURLOPT_ERRORBUFFER, CURLOPT_CASETYPE_OBJECTPOINT, 10)

			CURLOPT_CASE(CURLOPT_WRITEFUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 11)

			CURLOPT_CASE(CURLOPT_READFUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 12)

			CURLOPT_CASE(CURLOPT_TIMEOUT, CURLOPT_CASETYPE_LONG, 13)

			CURLOPT_CASE(CURLOPT_INFILESIZE, CURLOPT_CASETYPE_LONG, 14)

			CURLOPT_CASE(CURLOPT_POSTFIELDS, CURLOPT_CASETYPE_OBJECTPOINT, 15)

			CURLOPT_CASE(CURLOPT_REFERER, CURLOPT_CASETYPE_STRINGPOINT, 16)

			CURLOPT_CASE(CURLOPT_FTPPORT, CURLOPT_CASETYPE_STRINGPOINT, 17)

			CURLOPT_CASE(CURLOPT_USERAGENT, CURLOPT_CASETYPE_STRINGPOINT, 18)


			CURLOPT_CASE(CURLOPT_LOW_SPEED_LIMIT, CURLOPT_CASETYPE_LONG, 19)

			CURLOPT_CASE(CURLOPT_LOW_SPEED_TIME, CURLOPT_CASETYPE_LONG, 20)

			CURLOPT_CASE(CURLOPT_RESUME_FROM, CURLOPT_CASETYPE_LONG, 21)

			CURLOPT_CASE(CURLOPT_COOKIE, CURLOPT_CASETYPE_STRINGPOINT, 22)

			CURLOPT_CASE(CURLOPT_HTTPHEADER, CURLOPT_CASETYPE_SLISTPOINT, 23)

			CURLOPT_CASE(CURLOPT_HTTPPOST, CURLOPT_CASETYPE_OBJECTPOINT, 24)

			CURLOPT_CASE(CURLOPT_SSLCERT, CURLOPT_CASETYPE_STRINGPOINT, 25)

			CURLOPT_CASE(CURLOPT_KEYPASSWD, CURLOPT_CASETYPE_STRINGPOINT, 26)

			CURLOPT_CASE(CURLOPT_CRLF, CURLOPT_CASETYPE_LONG, 27)

			CURLOPT_CASE(CURLOPT_QUOTE, CURLOPT_CASETYPE_SLISTPOINT, 28)

			CURLOPT_CASE(CURLOPT_HEADERDATA, CURLOPT_CASETYPE_OBJECTPOINT, 29)

			CURLOPT_CASE(CURLOPT_COOKIEFILE, CURLOPT_CASETYPE_STRINGPOINT, 31)

			CURLOPT_CASE(CURLOPT_SSLVERSION, CURLOPT_CASETYPE_LONG, 32)

			CURLOPT_CASE(CURLOPT_TIMECONDITION, CURLOPT_CASETYPE_LONG, 33)

			CURLOPT_CASE(CURLOPT_TIMEVALUE, CURLOPT_CASETYPE_LONG, 34)


			CURLOPT_CASE(CURLOPT_CUSTOMREQUEST, CURLOPT_CASETYPE_STRINGPOINT, 36)

			CURLOPT_CASE(CURLOPT_STDERR, CURLOPT_CASETYPE_OBJECTPOINT, 37)


			CURLOPT_CASE(CURLOPT_POSTQUOTE, CURLOPT_CASETYPE_SLISTPOINT, 39)

			CURLOPT_CASE(CURLOPT_OBSOLETE40, CURLOPT_CASETYPE_OBJECTPOINT, 40)

			CURLOPT_CASE(CURLOPT_VERBOSE, CURLOPT_CASETYPE_LONG, 41)

			CURLOPT_CASE(CURLOPT_HEADER, CURLOPT_CASETYPE_LONG, 42)

			CURLOPT_CASE(CURLOPT_NOPROGRESS, CURLOPT_CASETYPE_LONG, 43)

			CURLOPT_CASE(CURLOPT_NOBODY, CURLOPT_CASETYPE_LONG, 44)

			CURLOPT_CASE(CURLOPT_FAILONERROR, CURLOPT_CASETYPE_LONG, 45)

			CURLOPT_CASE(CURLOPT_UPLOAD, CURLOPT_CASETYPE_LONG, 46)

			CURLOPT_CASE(CURLOPT_POST, CURLOPT_CASETYPE_LONG, 47)

			CURLOPT_CASE(CURLOPT_DIRLISTONLY, CURLOPT_CASETYPE_LONG, 48)

			CURLOPT_CASE(CURLOPT_APPEND, CURLOPT_CASETYPE_LONG, 50)

			CURLOPT_CASE(CURLOPT_NETRC, CURLOPT_CASETYPE_LONG, 51)

			CURLOPT_CASE(CURLOPT_FOLLOWLOCATION, CURLOPT_CASETYPE_LONG, 52)

			CURLOPT_CASE(CURLOPT_TRANSFERTEXT, CURLOPT_CASETYPE_LONG, 53)

			CURLOPT_CASE(CURLOPT_PUT, CURLOPT_CASETYPE_LONG, 54)


			CURLOPT_CASE(CURLOPT_PROGRESSFUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 56)

			CURLOPT_CASE(CURLOPT_PROGRESSDATA, CURLOPT_CASETYPE_OBJECTPOINT, 57)


			CURLOPT_CASE(CURLOPT_AUTOREFERER, CURLOPT_CASETYPE_LONG, 58)

			CURLOPT_CASE(CURLOPT_PROXYPORT, CURLOPT_CASETYPE_LONG, 59)

			CURLOPT_CASE(CURLOPT_POSTFIELDSIZE, CURLOPT_CASETYPE_LONG, 60)

			CURLOPT_CASE(CURLOPT_HTTPPROXYTUNNEL, CURLOPT_CASETYPE_LONG, 61)

			CURLOPT_CASE(CURLOPT_INTERFACE, CURLOPT_CASETYPE_STRINGPOINT, 62)

			CURLOPT_CASE(CURLOPT_KRBLEVEL, CURLOPT_CASETYPE_STRINGPOINT, 63)

			CURLOPT_CASE(CURLOPT_SSL_VERIFYPEER, CURLOPT_CASETYPE_LONG, 64)

			CURLOPT_CASE(CURLOPT_CAINFO, CURLOPT_CASETYPE_STRINGPOINT, 65)


			CURLOPT_CASE(CURLOPT_MAXREDIRS, CURLOPT_CASETYPE_LONG, 68)

			CURLOPT_CASE(CURLOPT_FILETIME, CURLOPT_CASETYPE_LONG, 69)

			CURLOPT_CASE(CURLOPT_TELNETOPTIONS, CURLOPT_CASETYPE_SLISTPOINT, 70)

			CURLOPT_CASE(CURLOPT_MAXCONNECTS, CURLOPT_CASETYPE_LONG, 71)

			CURLOPT_CASE(CURLOPT_OBSOLETE72, CURLOPT_CASETYPE_LONG, 72)


			CURLOPT_CASE(CURLOPT_FRESH_CONNECT, CURLOPT_CASETYPE_LONG, 74)

			CURLOPT_CASE(CURLOPT_FORBID_REUSE, CURLOPT_CASETYPE_LONG, 75)

			CURLOPT_CASE(CURLOPT_RANDOM_FILE, CURLOPT_CASETYPE_STRINGPOINT, 76)

			CURLOPT_CASE(CURLOPT_EGDSOCKET, CURLOPT_CASETYPE_STRINGPOINT, 77)

			CURLOPT_CASE(CURLOPT_CONNECTTIMEOUT, CURLOPT_CASETYPE_LONG, 78)

			CURLOPT_CASE(CURLOPT_HEADERFUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 79)

			CURLOPT_CASE(CURLOPT_HTTPGET, CURLOPT_CASETYPE_LONG, 80)

			CURLOPT_CASE(CURLOPT_SSL_VERIFYHOST, CURLOPT_CASETYPE_LONG, 81)

			CURLOPT_CASE(CURLOPT_COOKIEJAR, CURLOPT_CASETYPE_STRINGPOINT, 82)

			CURLOPT_CASE(CURLOPT_SSL_CIPHER_LIST, CURLOPT_CASETYPE_STRINGPOINT, 83)

			CURLOPT_CASE(CURLOPT_HTTP_VERSION, CURLOPT_CASETYPE_LONG, 84)

			CURLOPT_CASE(CURLOPT_FTP_USE_EPSV, CURLOPT_CASETYPE_LONG, 85)

			CURLOPT_CASE(CURLOPT_SSLCERTTYPE, CURLOPT_CASETYPE_STRINGPOINT, 86)

			CURLOPT_CASE(CURLOPT_SSLKEY, CURLOPT_CASETYPE_STRINGPOINT, 87)

			CURLOPT_CASE(CURLOPT_SSLKEYTYPE, CURLOPT_CASETYPE_STRINGPOINT, 88)

			CURLOPT_CASE(CURLOPT_SSLENGINE, CURLOPT_CASETYPE_STRINGPOINT, 89)

			CURLOPT_CASE(CURLOPT_SSLENGINE_DEFAULT, CURLOPT_CASETYPE_LONG, 90)

			CURLOPT_CASE(CURLOPT_DNS_USE_GLOBAL_CACHE, CURLOPT_CASETYPE_LONG, 91)

			CURLOPT_CASE(CURLOPT_DNS_CACHE_TIMEOUT, CURLOPT_CASETYPE_LONG, 92)

			CURLOPT_CASE(CURLOPT_PREQUOTE, CURLOPT_CASETYPE_SLISTPOINT, 93)

			CURLOPT_CASE(CURLOPT_DEBUGFUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 94)

			CURLOPT_CASE(CURLOPT_DEBUGDATA, CURLOPT_CASETYPE_OBJECTPOINT, 95)

			CURLOPT_CASE(CURLOPT_COOKIESESSION, CURLOPT_CASETYPE_LONG, 96)

			CURLOPT_CASE(CURLOPT_CAPATH, CURLOPT_CASETYPE_STRINGPOINT, 97)

			CURLOPT_CASE(CURLOPT_BUFFERSIZE, CURLOPT_CASETYPE_LONG, 98)

			CURLOPT_CASE(CURLOPT_NOSIGNAL, CURLOPT_CASETYPE_LONG, 99)

			CURLOPT_CASE(CURLOPT_SHARE, CURLOPT_CASETYPE_OBJECTPOINT, 100)

			CURLOPT_CASE(CURLOPT_PROXYTYPE, CURLOPT_CASETYPE_LONG, 101)

			CURLOPT_CASE(CURLOPT_ACCEPT_ENCODING, CURLOPT_CASETYPE_STRINGPOINT, 102)

			CURLOPT_CASE(CURLOPT_PRIVATE, CURLOPT_CASETYPE_OBJECTPOINT, 103)

			CURLOPT_CASE(CURLOPT_HTTP200ALIASES, CURLOPT_CASETYPE_SLISTPOINT, 104)

			CURLOPT_CASE(CURLOPT_UNRESTRICTED_AUTH, CURLOPT_CASETYPE_LONG, 105)

			CURLOPT_CASE(CURLOPT_FTP_USE_EPRT, CURLOPT_CASETYPE_LONG, 106)

			CURLOPT_CASE(CURLOPT_HTTPAUTH, CURLOPT_CASETYPE_LONG, 107)

			CURLOPT_CASE(CURLOPT_SSL_CTX_FUNCTION, CURLOPT_CASETYPE_FUNCTIONPOINT, 108)

			CURLOPT_CASE(CURLOPT_SSL_CTX_DATA, CURLOPT_CASETYPE_OBJECTPOINT, 109)

			CURLOPT_CASE(CURLOPT_FTP_CREATE_MISSING_DIRS, CURLOPT_CASETYPE_LONG, 110)

			CURLOPT_CASE(CURLOPT_PROXYAUTH, CURLOPT_CASETYPE_LONG, 111)

			CURLOPT_CASE(CURLOPT_FTP_RESPONSE_TIMEOUT, CURLOPT_CASETYPE_LONG, 112)

	default:
		logger("Unknwon %d\n", tag);
	}
}



typedef size_t(*header_callback_ptr)(char* buffer, size_t size, size_t nitems, void* userdata);

header_callback_ptr header_callback_orig = NULL;

size_t header_callback(char* buffer, size_t size, size_t nitems, void* userdata) {
	//logger("got header here %.*s\n", nitems, buffer);

	return header_callback_orig(buffer, size, nitems, userdata);
}


typedef size_t (*write_callback_ptr)(char* ptr, size_t size, size_t nmemb, void* userdata);
write_callback_ptr write_callback_orig = NULL;
size_t write_callback(char* ptr, size_t size, size_t nmemb, void* userdata) {

	//logger("got write(%p) here(%d) %.*s\n", userdata, nmemb, nmemb, ptr);
	//fprintf(write_file, "%.*s\n", nmemb, ptr);

	/*

	char tmp[255];
	sprintf(tmp, "[REDACTED]\\%p.txt", userdata);

	FILE* fp = fopen(tmp, "a+");
	fwrite(ptr, nmemb, size, fp);
	fclose(fp);
	*/
	return write_callback_orig(ptr, size, nmemb, userdata);
}


typedef size_t (*read_callback_ptr)(char* buffer, size_t size, size_t nitems, void* userdata);
read_callback_ptr read_callback_orig = NULL;
size_t read_callback(char* buffer, size_t size, size_t nitems, void* userdata) {

	size_t ret = read_callback_orig(buffer, size, nitems, userdata);
	//logger("got read here %.*s\n", ret, buffer);
	//fprintf(read_file, "%.*s\n", ret, buffer);
	return ret;
}

DWORD64 curl_easy_setopt(struct Curl_easy* data, DWORD64 tag, ...)
{
	print_setopt(tag);
	va_list arg;
	DWORD64 result;

	if (!data)
		return 43;

	va_start(arg, tag);


	if (tag == CURLOPT_HEADERFUNCTION) {

		header_callback_ptr tmp = va_arg(arg, header_callback_ptr);

		if (tmp != header_callback) {
			logger("Will spoof header callback with %p\n", header_callback);
			header_callback_orig = tmp;
			return curl_easy_setopt(data, tag, header_callback);
		}

		va_end(arg);
		va_start(arg, tag);
	}
	else if (tag == CURLOPT_WRITEFUNCTION) {

		write_callback_ptr tmp = va_arg(arg, write_callback_ptr);
		
		if (tmp != write_callback) {
			logger("Will spoof write callback %p\n", write_callback);
			write_callback_orig = tmp;
			return curl_easy_setopt(data, tag, write_callback);
		}

		va_end(arg);
		va_start(arg, tag);
	}
	else if (tag == CURLOPT_READFUNCTION) {

		read_callback_ptr tmp = va_arg(arg, read_callback_ptr);

		if (tmp != read_callback) {
			logger("Will spoof read callback %p\n", read_callback);
			read_callback_orig = tmp;
			return curl_easy_setopt(data, tag, read_callback);
		}

		va_end(arg);
		va_start(arg, tag);
	}
	else if (tag == CURLOPT_WRITEDATA) {
		char* ptr = va_arg(arg, char*);
		logger("Setting up data in (%p)\n", ptr);

		va_end(arg);
		va_start(arg, tag);
	}
	else if (tag == CURLOPT_ACCEPT_ENCODING) {
		printf("Ignoring encoding\n");
		va_end(arg);
		return 0;
	}

	result = curl_vsetopt_orig(data, tag, arg);

	va_end(arg);




	if (tag == CURLOPT_URL) {
		va_start(arg, tag);
		char* url = va_arg(arg, char*);
		logger("URL is %s\n", url);
		va_end(arg);
	}
	if (tag == CURLOPT_HEADERFUNCTION) {
		va_start(arg, tag);
		char* function = va_arg(arg, char*);
		logger("HEADERFUNCTION is %p\n", function);
		va_end(arg);
	}

	if (tag == CURLOPT_URL){
		curl_easy_setopt(data, CURLOPT_SSL_VERIFYHOST, 0);
		curl_easy_setopt(data, CURLOPT_SSL_VERIFYPEER, 0);
	}
	return result;
}

typedef void (*getdllhandle_ptr)(void*, void*, PUNICODE_STRING, PHANDLE);

getdllhandle_ptr getdllhandle = NULL;

INT WSAAPI getaddrinfo_hook(PCSTR pNodeName, PCSTR pServiceName, const ADDRINFOA* pHints,PADDRINFOA* ppResult) {

	logger("getaddrinfo of %s\n", pNodeName);
	INT res = getaddrinfo("localhost", pServiceName, pHints, ppResult);
	return res;
}

void setup_loader() {

	
	HMODULE value = LoadLibraryA("osdk_orig.dll");
	



	DWORD64 allocatorInit = GetProcAddress(value, "osdk_Allocator_Init");
	logger("PILAAA %d %p %p\n", GetModuleHandleA(NULL), value, allocatorInit);

	DWORD lmao;
	VirtualProtect(allocatorInit - 0xB0470, 0xEA000, PAGE_EXECUTE_READWRITE, &lmao);


	curl_vsetopt_orig = allocatorInit - 0x94E10;
	HookFunc(allocatorInit-0x92D60, curl_easy_setopt, "Hooking curl_easy_setopt\n");


	DWORD64 addressGetAddr = &getaddrinfo_hook;
	VirtualProtect(allocatorInit + 0x3A210, 8, PAGE_READWRITE, &lmao);
	memcpy(allocatorInit + 0x3A210, &addressGetAddr, sizeof(addressGetAddr));
	logger("getaddrinfo has been hooked\n");
	
	/*
	DWORD64 multiPerform = allocatorInit - 0x9AD40;
	logger("multi perform %p\n", multiPerform);

	DWORD64 multiSetOpt = allocatorInit - 0x9AA20;
	logger("multi SetOpt %p\n", multiSetOpt);


	DWORD64 serviceExecute = allocatorInit - 0xAA10;
	logger("serviceExcute %p\n", serviceExecute);

	DWORD64 biggestSender = allocatorInit - 0x7B940;
	logger("biggestSender %p\n", biggestSender);

	DWORD64 causesSend = allocatorInit - 0xA3CF0;
	logger("causesSend %p\n", causesSend);
	*/
}



BOOL WINAPI DllMain(HINSTANCE hInstDll, DWORD fdwReason, LPVOID reserverd) {

	if (fdwReason == DLL_PROCESS_ATTACH) {
		AllocConsole();

		/*
		packets = fopen("[REDACTED]\\packets.txt", "w");
		read_file = fopen("[REDACTED]\\read_packets.txt", "w");
		write_file = fopen("[REDACTED]\\write_packets.txt", "w");
		*/

		if (!freopen("CONOUT$", "w", stdout)) {
			MessageBoxA(NULL, "Error", "Couldn't allocate console...Closing", 0);
			return FALSE;
		}

		logger("Avengers Hook 6969 %d\n", sizeof(DWORD64));
		setup_loader();
		

		
	}
	else if (fdwReason == DLL_PROCESS_DETACH)
		FreeConsole();

	return TRUE;
}